version: '3'
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    container_name: rest-service
    environment:
      - PORT=${PORT}
    restart: always
    volumes:
      - ./logs:/usr/src/app/logs
      - ./db:/usr/src/app/db
      - ./src:/usr/src/app/src
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
volumes:
  pgdata:
