version: '3'

services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    container_name: rest-service
    environment:
      - PORT=${PORT}
    restart: always
    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
    networks:
      - my-network
    depends_on:
      - postgres
  postgres:
    build: ./dbNew
    container_name: 'postgres'
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - my-network
    volumes:
      - ./dbData:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge
